name: Release Drafter

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        required: true
        description: "Log level"
        default: "warning"

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
